# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='photo',
            new_name='photo_url',
        ),
        migrations.AlterField(
            model_name='chef',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='credit_card',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
