# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0002_auto_20161105_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='delivery_type',
            field=models.CharField(choices=[('NS', 'NO_STATE'), ('CO', 'CARRY_OUT'), ('DE', 'DELIVERY'), ('BO', 'BOTH')], default='NO_STATE', max_length=2),
        ),
    ]
