# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0003_chef_delivery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='name',
            new_name='username',
        ),
    ]
